#!/usr/bin/env php
<?php

use Illuminate\Foundation\Application;
use Illuminate\Http\Request;

define('LARAVEL_START', microtime(true));

// Register the Composer autoloader...
require __DIR__.'/vendor/autoload.php';

// Bootstrap Laravel and handle the command...
$app = require_once __DIR__.'/bootstrap/app.php';

if (PHP_SAPI === 'cli') {
    $status = $app->handleCommand(new Symfony\Component\Console\Input\ArgvInput);
    exit($status);
} else {
    $app->handleRequest(Request::capture());
}
